// src/components/organisms/Hero.svelte
<script>
  import Highlight from '../atoms/Highlight.svelte'
  import Heading from '../atoms/Heading.svelte'
  import Text from '../atoms/Text.svelte'
  import ProfilePicture from '../atoms/ProfilePicture.svelte'
</script>

<style lang="scss">
  section {
    display: grid;
    grid-auto-rows: 1fr;
    grid-auto-flow: row;
    grid-gap: auto;
    margin: 0 auto 20rem;

    @media screen and (min-width: 60rem) {
      grid-auto-flow: column;
      justify-content: space-between;
    }
    @media screen and (min-width: 100rem) {
      grid-template-columns: 60rem auto;
    }

    @media screen and (min-width: 120rem) {
      grid-template-columns: 80rem auto;
    }
  }
</style>

<section>
  <div>
    <Heading>
      Ik maak
      <Highlight>unieke</Highlight>
      en
      <Highlight>onvergetelijke</Highlight>
      ervaringen.
    </Heading>
    <Text bold>
      Ik ben een Communication & Multimedia Design student gevestigd in
      Amsterdam. Ik draag graag bij aan web- en mobiele apps die geven om de
      tijd en wensen van hun gebruikers.
    </Text>
  </div>
  <ProfilePicture src="/profile-picture.jpg" />
</section>

// src/components/Hero/Hero.tsx
import { Flex } from 'theme-ui'
import { LargeParagraph } from '../Text'
import { HeroHeading } from './Heading'

export const Hero: React.FC = () => (
  <Flex
    as="section"
    sx={{
      flexDirection: 'column',
      justifyContent: 'center',
      height: ['1', null, null, '80vh'],
    }}
  >
    <HeroHeading>Ik bouw ervaringen die bij mensen blijven hangen</HeroHeading>
    <LargeParagraph>
      Ik ben een Communication &amp; Multimedia Design student gevestigd in
      Amsterdam. Ik draag graag bij aan web- en mobiele apps die waarde geven,
      in plaats van tijd wegnemen. Mijn focus ligt altijd op de gebruiker, en
      wil elke ervaring voor hen zo soepel mogelijk te maken.
    </LargeParagraph>
  </Flex>
)
